export const past_speakers_data = [
  {
    name: "Vijender Singh Chauhan",
    des: "Associate Professor @DU, Interviewer & TEDx speaker",
    imgURL: "/pastspeaker/vijchau.png",
    xURL: "",
    instaURL: "",
    linkedinURL: "",
  },
  {
    name: "Sanjay Sethi",
    des: "Co-Founder & CEO, @Shopclues",
    imgURL: "/pastspeaker/sanjaysethi.png",
    xURL: "",
    instaURL: "",
    linkedinURL: "",
  },
  {
    name: "Kaustav Mukherjee",
    des: "Managing Director, BCG",
    imgURL: "/pastspeaker/Kaustav Mukherjee.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/smartbong/?originalSubdomain=in",
  },
  {
    name: "Ganesh Rengaswami",
    des: "Co-Founder &Managing Partner, Quona Capiral",
    imgURL: "/pastspeaker/Ganesh Rengaswamy.jpg",
    xURL: "https://twitter.com/grengaswamy",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/ganeshrengaswamy/?originalSubdomain=sg",
  },
  {
    name: "Sandeep Jain",
    des: "Founder, CEO, GFG",
    imgURL: "/pastspeaker/Sandeep Jain.jpg",
    xURL: "https://twitter.com/sandeep_jain",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/sandeep-jain-/?originalSubdomain=in",
  },
  {
    name: "Amit Somani",
    des: "Managing partner, Prime ventures",
    imgURL: "/pastspeaker/Amit Somani.jpg",
    xURL: "https://twitter.com/amitsomani",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/thesomani/?originalSubdomain=in",
  },
  {
    name: "Anubhav Dubey",
    des: "CO-Founder, Chai Sutta Bar",
    imgURL: "/pastspeaker/Anubhav Dube.jpg",
    xURL: "https://twitter.com/tbhanubhav?lang=en",
    instaURL: "https://www.instagram.com/anubhavdubey1/?hl=en",
    linkedinURL:
      "https://www.linkedin.com/in/anubhavdubey/?originalSubdomain=in",
  },
  {
    name: "Krishna Vedati",
    des: "Co-Founder and CEO, Tynker",
    imgURL: "/pastspeaker/Krishna Vedati.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/krishnavedati/",
  },
  {
    name: "BV Jagaddesh",
    des: "Managing Director, Kaaj Ventures",
    imgURL: "/pastspeaker/BV Jagadeesh.jpg",
    xURL: "https://twitter.com/bvjagadeesh?lang=en",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/bvjagadeesh/",
  },
  {
    name: "Aditi Pal",
    des: "CFO, Bewkoof.com",
    imgURL: "/pastspeaker/Aditi Pal.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/aditi-pai-67383281/?originalSubdomain=in",
  },
  {
    name: "Priya Sharma",
    des: "Co-Founder, ZestMoney",
    imgURL: "/pastspeaker/Priya Sharma.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/priya-sharma-635a223/?originalSubdomain=in",
  },
  {
    name: "Sachin Tomar",
    des: "Co-founder and CTO, Biconomy",
    imgURL: "/pastspeaker/Sachin Tomar.jpg",
    xURL: "https://twitter.com/schin_tomar?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/sachintomar2271/?originalSubdomain=ae",
  },
  {
    name: "Gunjan Shukla",
    des: "ex-CFO, Paypal",
    imgURL: "/pastspeaker/Gunjan Shukla.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/gunjanshukla/?originalSubdomain=in",
  },
  {
    name: "Garv Malik",
    des: "CMO, Slice",
    imgURL: "/pastspeaker/Garv Malik.jpg",
    xURL: "https://twitter.com/malikgarv?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor",
    instaURL: "https://www.instagram.com/imgarvmalik/?hl=en",
    linkedinURL:
      "https://www.linkedin.com/in/gunjanshukla/?originalSubdomain=in",
  },
  {
    name: "Gaurav Agarwal",
    des: "Co-Founder, 1MG",
    imgURL: "/pastspeaker/Gaurav Agarwal.jpg",
    xURL: "https://twitter.com/agarwal_gaurav?lang=en",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/agarwalga/?originalSubdomain=in",
  },
  {
    name: "Deepak Tuli",
    des: "co-founder and ex-coo, goibibo and Eka Care",
    imgURL: "/pastspeaker/Deepak Tuli.jpg",
    xURL: "https://twitter.com/deepaktuli",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/deepak-tuli-62a8617/?originalSubdomain=in",
  },
  {
    name: "Amit Kumar Agarwal",
    des: "Founder and CEO, Nobroker",
    imgURL: "/pastspeaker/Amit Kumar Agarwal.jpg",
    xURL: "https://twitter.com/amitkumara?lang=en",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/amit-kumar-agarwal-5b30301/?originalSubdomain=in",
  },
  {
    name: "Piyush Agarwal",
    des: "Founder, Director at crickbuzz",
    imgURL: "/pastspeaker/Piyush Agarwal.jpg",
    xURL: "https://twitter.com/piyush_agrawal",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/piyushagrawal2/?originalSubdomain=in",
  },
  {
    name: "Dr Radhakrishnan Pillai ",
    des: "Cheif Leadership Coach, Chanakya Aanvikshiki",
    imgURL: "/pastspeaker/Dr. Radhakrishnan Pillai.jpg",
    xURL: "https://twitter.com/rchanakyapillai",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/rchanakyapillai/?originalSubdomain=in",
  },
  {
    name: "Dr Sangita Reddy",
    des: "MD, Apollo Hospitals",
    imgURL: "/pastspeaker/Dr. Sangita Reddy.jpg",
    xURL: "https://twitter.com/drsangitareddy",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/drsangitareddy/?originalSubdomain=in",
  },
  {
    name: "Vishal Jindal",
    des: "Founder and Co CEO, Biryani By Kilo",
    imgURL: "/pastspeaker/Vishal Jindal.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/vishal-jindal-7424282/?originalSubdomain=in",
  },

  {
    name: "Praharsh Sharma",
    des: "MD, Goldman Sachs",
    imgURL: "/pastspeaker/Praharsh Sharma.jpg",
    xURL: "https://twitter.com/praharsh_sharma",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/praharsh/?originalSubdomain=in",
  },

  {
    name: "Sanjeev Mehta",
    des: "MD, Standard chartered Bank India",
    imgURL: "/pastspeaker/Sanjeev Mehta.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/sanjeevmehtascbank/?originalSubdomain=in",
  },
  {
    name: "Amitava Saha",
    des: "Co-Founder and CEO, XpressBees and FirstCry",
    imgURL: "/pastspeaker/AmitavaSaha.jpeg",
    xURL: "",
    instaURL: "",
    linkedinURL:
      "https://www.linkedin.com/in/amitavasaha73/?originalSubdomain=in",
  },

  {
    name: "Vishwanathan Iyer",
    des: "VP Sales & Architecture, CISCO",
    imgURL: "/pastspeaker/Vishwanathan Iyer.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/vishviyer/?originalSubdomain=sg",
  },

  {
    name: "Ankit Aggarwal",
    des: "Founder & CEO, Unstop",
    imgURL: "/pastspeaker/Ankit Aggarwal.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/unstoppableankit/",
  },

  {
    name: "Murli Thirumale",
    des: "Co-Founder & VP, Portworx",
    imgURL: "/pastspeaker/Murli Thirumale.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/murlithirumale/",
  },
  {
    name: "Dharamveer Singh Chauhan",
    des: "Co-Founder and CEO, Zo World and Zostel",
    imgURL: "/pastspeaker/Dharamveer Singh Chouhan.jpg",
    xURL: "https://twitter.com/dvcoolster",
    instaURL: "https://www.instagram.com/dvcoolster/?hl=en",
    linkedinURL: "https://www.linkedin.com/in/dvcoolster/?originalSubdomain=in",
  },
  {
    name: "Ankur Warikoo",
    des: "Founder @Webveda",
    imgURL: "/presentspeaker/ankur.png",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/warikoo/?originalSubdomain=in",
  },
  {
    name: "Amit Kataria",
    des: "CoFoudnder and Chief operating officer @ SARAS AI",
    imgURL: "/presentspeaker/amit.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/amitkatarianeted/?originalSubdomain=in",
  },
  {
    name: "Avi Dutt",
    des: "Head, IIT BHU Seed Fund",
    imgURL: "/presentspeaker/avi.png",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/avi-dutt/",
  },
  {
    name: "Dhruv Agarwala",
    des: "Chief Executive Officer at REA India Pte. Ltd.(Housing.com, Proptiger.com & Makaan.com)",
    imgURL: "/presentspeaker/dhruv.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/dhruv-agarwala-ba724/",
  },
  {
    name: "Shailesh Kumar",
    des: "Chief Success Officer at Saras AI  ",
    imgURL: "/presentspeaker/shailesh.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/coachshailesh/?originalSubdomain=in",
  },
  {
    name: "Kumar Bagrodia ",
    des: "Founder, Lead Neuroscientist at NeuroLeap",
    imgURL: "/presentspeaker/kumar.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/kbagrodia/",
  },
  {
    name: "Kshitiz Aggarwal ",
    des: "Asia Lead - Data & AI, Microsoft",
    imgURL: "/presentspeaker/kshitiz.png",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/kshitizaggarwal/",
  },
  {
    name: " Shashi Bhargava ",
    des: "Executive Vice President at Datamatics",
    imgURL: "/presentspeaker/shashi.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/shashi-bhargava-7063233/",
  },
  {
    name: " Vishwas Jain ",
    des: "Senior Data Scientist at MasterCard ",
    imgURL: "/presentspeaker/vishwas.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/vishwas-jain3/",
  },
  {
    name: "Aman Gupta ",
    des: "CTO at Saras AI ",
    imgURL: "/presentspeaker/aman.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/amangupta15/",
  },
  {
    name: "Anirban Ghosh ",
    des: "AVP - E-Commerce at Sugar Cosmetics ",
    imgURL: "/presentspeaker/anirban.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/anirbanghosh1/",
  },
  {
    name: "Gunit Dhingra ",
    des: "Lead Product Manager at MakeMyTrip ",
    imgURL: "/presentspeaker/gunit.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/gunit-dhingra-6469a2143/",
  },
  {
    name: "Manan Singhal ",
    des: "Director, Strategy at Zepto ",
    imgURL: "/presentspeaker/manan.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/manan-singhal-886786145/",
  },
  {
    name: "Parag Agarwal ",
    des: "Founder at Unconsult, ex-COO at Akash, and SVP at Indiamart ",
    imgURL: "/presentspeaker/parag.png",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/1parag/",
  },
  {
    name: "Chinmaya Sharma ",
    des: "Partner at Info Edge Ventures ",
    imgURL: "/presentspeaker/chinmaya.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/chinmaya-sharma/",
  },
  {
    name: "Manan Anand ",
    des: "Investor at GrowX Ventures",
    imgURL: "/presentspeaker/anand.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/manan-anand12/",
  },
  {
    name: "Saurabh Singh ",
    des: "Director at Trifecta Capital ",
    imgURL: "/presentspeaker/saurabh.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/saurabh-singh-bb6b4022/",
  },
  {
    name: "Gautam Ravi ",
    des: "Early Stage Investor at WEH Ventures ",
    imgURL: "/presentspeaker/gautam.jpg",
    xURL: "",
    instaURL: "",
    linkedinURL: "https://www.linkedin.com/in/gautamravi192/",
  },
];

export const present_speakers_data = [
   
  
];
